version: '3'

services:

  system-eureka-namng-server-service:
    image: system-eureka-namng-server-service
    container_name: system-eureka-naming-server-service
    build:
      context: ./system-eureka-naming-server-service
      dockerfile: Dockerfile
    ports:
      - "8761:8761"
    networks:
      - network
  
  custom-text-service:
    image: custom-text-service
    container_name: custom-text-service
    build:
      context: ./custom-text-service
      dockerfile: Dockerfile
    ports:
      - "9090:9090"
    networks:
      - network
    depends_on:
      - system-eureka-namng-server-service

  custom-greeting-service:
    image: custom-greeting-service
    container_name: custom-greeting-service
    build:
      context: ./custom-greeting-service
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - network
    depends_on:
      - custom-text-service
      - system-eureka-namng-server-service

networks:
  network:
    name: custom-network