spring:
  application:
    name: custom-greeting-service

custom-text-service-ribbon:
  ribbon:
    eureka:
      enabled: false
    listOfServers: custom-text-service
    ServerListRefreshInterval: 2000

server:
  port: ${port:8080}