spring:
  application:
    name: custom-greeting-service

server:
  port: ${port:8080}

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER:http://system-eureka-naming-server-service:8761/eureka}